
/*******************************************************************************/
/* "GTK" drawing routines for the Fast Light Tool Kit (FLTK).                  */
/*                                                                             */
/* These box types provide a GTK+ look, based on Red Hat's Bluecurve           */
/* theme..                                                                     */
/* Copyright 2006-2010 by Michael Sweet.                                       */
/* Copyright 2024- Stazed                                                      */
/*                                                                             */
/* This program is free software; you can redistribute it and/or modify it     */
/* under the terms of the GNU General Public License as published by the       */
/* Free Software Foundation; either version 2 of the License, or (at your      */
/* option) any later version.                                                  */
/*                                                                             */
/* This program is distributed in the hope that it will be useful, but WITHOUT */
/* ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or       */
/* FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for   */
/* more details.                                                               */
/*                                                                             */
/* You should have received a copy of the GNU General Public License along     */
/* with This program; see the file COPYING.  If not,write to the Free Software */
/* Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.  */
/*******************************************************************************/

void init_gtk_theme ( void );
